version: '3'

services:
  app:
    build: .
    environment:
      - API_ID=API_ID
      - API_HASH=API_HASH
      - SESSION_NAME=SESSION_NAME
      - PHONE_NUMBER=PHONE_NUMBER
      - AUTH_CODE=YOUR_AUTH_CODE
    volumes:
      - .:/app
    command: ["python", "main.py"]

